[task_local]
0 9 * * * https://raw.githubusercontent.com/s1sunny/quanx_scripts/refs/heads/main/app/hcz/hcz.js, tag=平安好车主签到, enabled=true

[rewrite_local]
^https:\/\/hcz-member\.pingan\.com\.cn\/micro-api\/.* url script-request-body https://raw.githubusercontent.com/s1sunny/quanx_scripts/refs/heads/main/app/hcz/hcz.js

[mitm]
hostname = hcz-member.pingan.com.cn, icore-hczhd.pingan.com.cn, hcz-static.pingan.com.cn, hcz-vass-img.pingan.com.cn