#******************************
# 脚本功能：平安好车主 ☆ 每日签到
# 仓库地址：https://github.com/s1sunny/quanx_scripts
# 脚本作者：s1sunny
# 更新时间：2026-07-02
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！
#*******************************
#[mitm]
hostname = hcz-member.pingan.com.cn, icore-hczhd.pingan.com.cn, hcz-static.pingan.com.cn

#[rewrite_local]
# 捕获 bo7friwl + spartaId（打开APP时自动获取）
^https:\/\/hcz-member\.pingan\.com\.cn\/micro-api\/.* url script-request-body https://raw.githubusercontent.com/s1sunny/quanx_scripts/refs/heads/main/app/hcz/hcz.js

#[task_local]
0 9 * * * https://raw.githubusercontent.com/s1sunny/quanx_scripts/refs/heads/main/app/hcz/hcz.js, tag=平安好车主签到, enabled=true