#******************************
# 脚本功能：长城汽车☆每日签到 + 盲盒抽奖
# 仓库地址：https://github.com/s1sunny/quanx_scripts
# 脚本作者：s1sunny
# 更新时间：2026-07-01
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！
#*******************************
#[mitm]
hostname = gapp-api.gwmapp-h.com

#[rewrite_local]
^https:\/\/gapp-api\.gwmapp-h\.com\/community-u\/v1\/app\/uc\/sign\/info url script-request-body https://raw.githubusercontent.com/s1sunny/quanx_scripts/refs/heads/main/app/gwm/gwm.js
