#******************************
# 脚本功能：合胜百货☆每日签到
# 仓库地址：https://github.com/s1sunny/quanx_scripts
# 脚本作者：s1sunny
# 更新时间：2026-07-01
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！
#*******************************
#[mitm]
hostname = 120.78.175.218

#[rewrite_local]
^https:\/\/120\.78\.175\.218\/EnjoyMobile_Core\/Enjoy\/Service url script-request-body https://raw.githubusercontent.com/s1sunny/quanx_scripts/refs/heads/main/app/hesheng/hesheng.js
