#******************************
# 脚本功能：美的会员☆每日签到
# 仓库地址：https://github.com/s1sunny/quanx_scripts
# 脚本作者：s1sunny
# 更新时间：2026-07-02
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！
#*******************************
#[mitm]
hostname = mvip.midea.cn, mcsp.midea.com, mcsp-api.midea.com

#[rewrite_local]
# 捕获 ucAccessToken（打开小程序时自动获取）
^https:\/\/mcsp\.midea\.com\/api\/cms_bff\/mcsp-uc-mvip-bff\/app\/login\/wx\/mini\/getLoginInfo\.do url script-response-body https://raw.githubusercontent.com/s1sunny/quanx_scripts/refs/heads/main/app/midea/midea.js

#[task_local]
0 8 * * * https://raw.githubusercontent.com/s1sunny/quanx_scripts/refs/heads/main/app/midea/midea.js, tag=美的会员签到, enabled=true
