#******************************
# 脚本功能：南网在线☆每日签到 + 电费账单任务(50积分/月)
# 仓库地址：https://github.com/s1sunny/quanx_scripts
# 脚本作者：s1sunny
# 更新时间：2026-06-30
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！
#*******************************
[mitm]
hostname = 95598.csg.cn

[rewrite_local]
^https:\/\/95598\.csg\.cn\/mp\/w2\/szfw-points-txhsj\/ url script-request-body https://raw.githubusercontent.com/s1sunny/quanx_scripts/refs/heads/main/app/nfdaily/nfdaily.js
